# Generated by Django 4.0.1 on 2022-02-02 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_remove_reservation_date_added_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='auto_bay_id',
            new_name='auto_bay_name',
        ),
    ]
