# Generated by Django 4.0.1 on 2022-02-02 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_rename_auto_bay_id_reservation_auto_bay_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='auto_bay_name',
            new_name='auto_bay_id',
        ),
    ]
