# Generated by Django 4.0.1 on 2022-02-04 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hunter_diy_garage', '0007_autobay_name'),
        ('reservations', '0004_rename_auto_bay_name_reservation_auto_bay_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='auto_bay_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='hunter_diy_garage.autobay'),
        ),
    ]
