# Generated by Django 4.0.1 on 2022-02-04 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_alter_reservation_auto_bay_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date_reserved',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
