# Generated by Django 4.0.1 on 2022-02-08 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_alter_reservation_diy_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='auto_bay_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='reservations', to='hunter_diy_garage.autobay'),
        ),
    ]
