# Generated by Django 4.0.1 on 2022-01-25 04:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hunter_diy_garage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electricity_used', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('hours_used', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('make', models.CharField(max_length=20)),
                ('checked_out', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Tools',
        ),
        migrations.RenameModel(
            old_name='AutoBays',
            new_name='AutoBay',
        ),
        migrations.AddField(
            model_name='reservation',
            name='auto_bay_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='hunter_diy_garage.autobay'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='diy_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL),
        ),
    ]
