# Generated by Django 4.0.1 on 2022-01-25 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hunter_diy_garage', '0002_reservation_tool_delete_tools_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeedleScaler',
            fields=[
                ('tool_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hunter_diy_garage.tool')),
            ],
            bases=('hunter_diy_garage.tool',),
        ),
        migrations.CreateModel(
            name='TorqueWrench',
            fields=[
                ('tool_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hunter_diy_garage.tool')),
            ],
            bases=('hunter_diy_garage.tool',),
        ),
        migrations.CreateModel(
            name='Welder',
            fields=[
                ('tool_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hunter_diy_garage.tool')),
            ],
            bases=('hunter_diy_garage.tool',),
        ),
        migrations.AddField(
            model_name='tool',
            name='num_times_checked_out',
            field=models.SmallIntegerField(default=0),
        ),
    ]
