# Generated by Django 4.0.1 on 2022-02-01 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunter_diy_garage', '0003_needlescaler_torquewrench_welder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='electricity_used',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='hours_used',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
