# Generated by Django 4.0.1 on 2022-02-02 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hunter_diy_garage', '0005_alter_tool_cost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
