# Generated by Django 4.0.1 on 2022-02-02 03:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hunter_diy_garage', '0006_delete_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='autobay',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
