# Generated by Django 4.0.1 on 2022-02-08 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunter_diy_garage', '0007_autobay_name'),
    ]

    operations = [

        migrations.AddField(
            model_name='tool',
            name='characteristic',
            field=models.CharField(choices=[('cordless', 'cordless'), ('air', 'air'), (
                'corded', 'corded'), ('undefined', 'undefined')], default='undefined', max_length=9),
        ),
        migrations.DeleteModel(
            name='NeedleScaler',
        ),
        migrations.DeleteModel(
            name='TorqueWrench',
        ),
        migrations.DeleteModel(
            name='Welder',
        ),
    ]
