# Generated by Django 4.0.1 on 2022-02-09 02:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hunter_diy_garage', '0008_remove_torquewrench_tool_ptr_remove_welder_tool_ptr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.IntegerField(unique=True)),
                ('expiration', models.DateField(auto_now=True)),
                ('security_code', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
