# Generated by Django 4.0.1 on 2022-02-01 02:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diy_users', '0003_alter_diyusers_email_alter_diyusers_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diyusers',
            name='phone_number',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. 10 digits allowed.", regex='\\d{10}')]),
        ),
    ]
