# Generated by Django 4.0.1 on 2022-02-10 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diy_users', '0006_alter_diyusers_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diyusers',
            name='reservation',
            field=models.BooleanField(null=True),
        ),
    ]
